name: Validate Submission(s)
on:
  pull_request_target:
    types: [synchronize]
    branches:
      - main
    paths: 
      - 'data-processed/**.parquet'

jobs:
    validates-files:
        runs-on: ubuntu-20.04

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 1

        - name: Setup R
          if: ( steps.change-check.outputs.skipnext  != 'true' ) 
          uses: r-lib/actions/setup-r@v2

        - name: Install system dependencies
          run: sudo apt-get install libcurl4-openssl-dev libudunits2-dev libgdal-dev


        - name: Cache R packages
          id: cache
          uses: actions/cache@v2
          with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-${{ hashFiles('.github/requirements.txt') }}-1

        - name: Install dependencies
          if: ( steps.change-check.outputs.skipnext  != 'true' )
          run: |
            R -e 'Sys.setenv("NOT_CRAN" = TRUE)
                  install.packages(c("arrow", "gh", "remotes"))
                  Sys.unsetenv("NOT_CRAN")
                  remotes::install_url("https://github.com/midas-network/SMHvalidation/archive/refs/heads/version.zip")
                  remotes::install_url("https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/archive/refs/heads/main.zip")'
          env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

        - name: Run Validation
          run: |
            Rscript code/validation.R
          env:
            GH_PR_NUMBER: ${{ github.event.pull_request.number }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
